apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: microsm/micro-scheduler:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_ADDR
          value: "redis-master:6379"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
